import Header from "@/Header"
import './globals.css'
import { Footer } from "@/Footer"
import { Menu } from "@/Menu/Menu"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  )
}
