export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export const A = () => {

}
export const B = () => {

}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
